### ISSUE TITLE
support heuristic callbacks

### ISSUE THREAD

**Issue by leethargo** [leethargo/SCIP.jl#5]
This should be easy to do, based on CSIP, but there are some challenges:

1. Incomplete solutions (with NaN values) are not currently support by SCIP and therefore CSIP. This feature (solution completion by neighborhood search) might be included in the next SCIP release, but even then it might only work for solution candidates added before the branch-and-bound process.

2. CSIP only supports adding one solution per callback call. It should be possible to refactor that code, though.

3. The tests from JuMP for heuristic callbacks fail on my initial implementation because the callback is never called. This is because the heuristic timing is set to `AFTERNODE` (which makes sense, because we then have the LP relaxation values) but the problem used in the tests is already solved during the root. Therefore, the solving is stopped before the heuristic is asked.

**Comment by mlubin** [comment]
> but the problem used in the tests is already during the root. Therefore, the solving is stopped before the heuristic is asked.

For some of the other solvers we disable features like preprocessing and cuts for this test so that the problem is *not* solved at the root.

**Comment by leethargo** [comment]
I also tried disabling presolve and heuristics, but didn't go far enough, it seems.

Of course, without support for incomplete solutions, the tests will still fail.

**Comment by mlubin** [comment]
Well, you can ignore incomplete solutions if you'd like.
